language: python

sudo: required

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6

before_install:
  - source .ci/travis_setup.sh
  # install non-python build requirements and switch to virtualenv if necessary
  - setup_environment
  # install python build requirements
  - python -m pip install -U -r python/dev_requirements.txt

install:
  - mkdir build
  - pushd build
  # build libraries
  - cmake ..
  - make
  # make python source distribution (for upload to PyPI)
  - make digital_rf_sdist
  # install python package into virtual environment for testing
  - python -m pip install dist/digital_rf-*.tar.gz
  # install python test requirements
  - python -m pip install -U pytest

script:
  # c tests
  - make test
  - rm -r /tmp/hdf5
  # python tests
  - pytest --maxfail=10 ./python/
  # return to base working directory
  - popd

# Note: TWINE_USERNAME and TWINE_PASSWORD are set in Travis settings
deploy:
  provider: script
  script: .ci/pypi_upload.sh build/dist/*
  skip_cleanup: true
  on:
    python: 2.7
    condition: $TRAVIS_OS_NAME == 'linux'
    tags: true
